### ISSUE TITLE
Editing a file won't work either :)

### ISSUE THREAD

**Issue by liimee** [Electogenius/request-counter#1]
Editing a file won't be saved on vercel either.. unless you can somehow [dispatch a GitHub Workflow thing that updates the file via the API](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event)

**Comment by Electogenius** [comment]
Yeah I did look it up, fs doesn’t work on vercel. I couldn’t really find if it works with netlify but eh

Hmm, maybe I could use this, and use my gh key as a vercel environment variable.

I don’t really know much about workflows, I should probably do some investigation 🔍 

I’ll try (yes I saw your fork, not sure what language it is, looks kinda like js but idk)

**Comment by liimee** [comment]
the fork doesn't even work lol, but I'll keep trying (I think because of some math, not sure though)

also, it's Bash

**Comment by Electogenius** [comment]
Oh, cool

(Huh I was right)


(Also yaml was made by evil alien AI alongside python and so should never be used)

also thanks thankssss
